### ISSUE TITLE
Backend - Login & Register View

### ISSUE THREAD

**Issue by PiotrRynio** [MateuszNaKodach/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments#203]
Bardzo proszę o pozostawienie tego komponentu dla mnie - chciałbym przebrnąć przez proces Front-Back w całości!
PiotrWR

**Comment by annalamperska** [comment]
Na to jest już chyba task - https://github.com/nowakprojects/CodersCamp2020.Project.FullStack-Node-React.TableSoccerTournaments/issues/42
